package sonata.open.drugsdosage.presentation.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00629D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC8E6FF)
val onPrimaryContainerLight = Color(0xFF001E2E)
val secondaryLight = Color(0xFF705D00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFE173)
val onSecondaryContainerLight = Color(0xFF221B00)
val tertiaryLight = Color(0xFF5C6300)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0EB69)
val onTertiaryContainerLight = Color(0xFF1B1D00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FAFE)
val onBackgroundLight = Color(0xFF181C20)
val surfaceLight = Color(0xFFF6FAFE)
val onSurfaceLight = Color(0xFF181C20)
val surfaceVariantLight = Color(0xFFDDE3EA)
val onSurfaceVariantLight = Color(0xFF41484D)
val outlineLight = Color(0xFF71787E)
val outlineVariantLight = Color(0xFFC1C7CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEEF1F6)
val inversePrimaryLight = Color(0xFF93CDF6)
val surfaceDimLight = Color(0xFFD7DADF)
val surfaceBrightLight = Color(0xFFF6FAFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F4F9)
val surfaceContainerLight = Color(0xFFEBEEF3)
val surfaceContainerHighLight = Color(0xFFE5E8ED)
val surfaceContainerHighestLight = Color(0xFFDFE3E7)


val primaryDark = Color(0xFF93CDF6)
val onPrimaryDark = Color(0xFF00344D)
val primaryContainerDark = Color(0xFF004C6D)
val onPrimaryContainerDark = Color(0xFFC8E6FF)
val secondaryDark = Color(0xFFDEC56E)
val onSecondaryDark = Color(0xFF3B2F00)
val secondaryContainerDark = Color(0xFF554500)
val onSecondaryContainerDark = Color(0xFFFBE186)
val tertiaryDark = Color(0xFF7C8500)
val onTertiaryDark = Color(0xFF2F3300)
val tertiaryContainerDark = Color(0xFF454B00)
val onTertiaryContainerDark = Color(0xFFE0EB69)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B2024)
val onBackgroundDark = Color(0xFFDFE3E7)
val surfaceDark = Color(0xFF242D33) // card color
val onSurfaceDark = Color(0xFFDFE3E7)
val surfaceVariantDark = Color(0xFF41484D)
val onSurfaceVariantDark = Color(0xFFC1C7CE)
val outlineDark = Color(0xFF8B9198)
val outlineVariantDark = Color(0xFF41484D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE3E7)
val inverseOnSurfaceDark = Color(0xFF2D3135)
val inversePrimaryDark = Color(0xFF236488)
val surfaceDimDark = Color(0xFF101417)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F12)
val surfaceContainerLowDark = Color(0xFF181C20)
val surfaceContainerDark = Color(0xFF1C2024)
val surfaceContainerHighDark = Color(0xFF262A2E)
val surfaceContainerHighestDark = Color(0xFF313539)










